const prodGamesList = ["Missonman","HillClimbRacing",
    "Basketball", "CollectingWT_P", "Rogue",
    "SlidingPuzzle",
    "BricksBreaker",
    "Snake",
    "ClickTheDifferentColor",
    "MathPuzzle",
    "DuckHunt",
    "TossTheCan",
    "Go-around", "CutTheRope", "CadburyGems(Memorydots)",
    "platformer-mickey-cheese", "Spaceshooter", "HappyB", "petGame", "WordDice",
    "Airshipadventure",
    "AngryBirds",
    "Basketball",
    "BoxTower",
    "BricksBreaker",
    "Bridgebuilder",
    "CadburyGems(Memorydots)",
    "CandyCrush",
    "CannonBalls",
    "CannonShooter",
    "cardMemory",
    "ChromeDinoRun",
    "ClickTheDifferentColor",
    "CollectingWT_P",
    "CrossyRoad",
    "CutTheRope",
    "Darts",
    "DownhillSki",
    "DuckHunt",
    "FightOn",
    "FightOn2",
    "FlappyBird",
    "FruitNinja",
    "Go-around",
    "HappyB",
    "Harpoon",
    "HillClimbRacing",
    "Mariobros",
    "MathPuzzle",
    "MessidodgeCorona",
    "Missonman",
    "Platformer(infiniteverticaljumping).js",
    "Pong.js",
    "Racing.js",
    "RiseUp.js",
    "saveEarth.js",
    "SpaceInvader.js",
    "SpinMaster.js",
    "SwingMania.js",
    "TaptoSave.js",
    "TowerDefence(Arcade-shooting-health).js",
    "Whack-a-Mole.js",
    "Go-around.js",
    "CutTheRope.js",

    "NinjaBlades.js"
]

export default prodGamesList;
